/**
 * truncinvbankbus.js — empties every transaction table behind the
 * Inventory, Banking, Purchase, and Sales menus (navConfig.js), including
 * their currently-hidden sub-menu items (Enquiry, Follow-up, Cheque Print).
 *
 *   npm run truncinvbankbus -- --yes
 *
 * DESTRUCTIVE AND IRREVERSIBLE. Without --yes it only prints what it would
 * delete and exits, matching src/scripts/empdepttrnck.js's own guard.
 *
 * ---------------------------------------------------------------------------
 * What's covered
 * ---------------------------------------------------------------------------
 * Inventory  : Stock Receipt, Stock Issue, Stock Adjustment,
 *              Stock Transfer (Request / Issue / Receipt)
 * Banking    : Deposit Entry, Bank Reconciliation, Cheque Print (hidden),
 *              Payment Receipt, Payment Voucher
 * Purchase   : Purchase Quotation, Purchase Order, Purchase GRN,
 *              Purchase Return, Purchase Invoice, Purchase Credit Memo
 * Sales      : Enquiry (hidden), Follow-up (hidden), Sales Quotation,
 *              Sales Order, Delivery Challan, Sales Return, Sales Invoice,
 *              Sales Credit Memo
 *
 * Plus three tables that are *generated by* those documents rather than
 * being a menu item themselves — left in place they'd reference documents
 * that no longer exist, so they're wiped alongside the documents that fed
 * them:
 *   - Stock                (the stock ledger — every Inventory/Purchase/
 *                            Sales posting above writes rows here)
 *   - CustomerOutstanding  (balance snapshots created by Sales Invoice)
 *   - SupplierOutstanding  (balance snapshots created by Purchase Invoice)
 *
 * Deliberately NOT touched: Collection Entry / Payment Entry and their
 * application tables (collections, supplier_payments, ...). Those live
 * under the separate, hidden Receivables/Payables menus — not Inventory,
 * Banking, Purchase, or Sales — and they're real documents a user entered,
 * not a derived summary. They only ever reference an invoice by its plain
 * text invoiceNo (no foreign key), so deleting the invoices above does not
 * touch them and does not break anything for them to keep existing.
 * Document Numbering (document_numbering) is also left alone on purpose —
 * it's configuration (prefixes, series, next-number counters), not
 * transaction data, and resetting it is a separate decision.
 *
 * ---------------------------------------------------------------------------
 * One table at a time, not batched
 * ---------------------------------------------------------------------------
 * Both the dry-run counts and the actual deletes run strictly one table at
 * a time (a plain sequential loop, not Promise.all / a single
 * multi-table $transaction) — this server can't take 51 queries or a
 * giant transaction spanning every table at once. Each table is fully
 * finished (counted, or deleted + identity reset) before the next one
 * starts, at the cost of the all-or-nothing guarantee one big transaction
 * would have given: if the run is interrupted partway through the delete
 * phase, whatever printed above tells you exactly where it stopped, and
 * re-running the script is safe — an already-emptied table just counts 0
 * and does nothing more.
 *
 * ---------------------------------------------------------------------------
 * Why DELETE + DBCC CHECKIDENT rather than an actual TRUNCATE TABLE
 * ---------------------------------------------------------------------------
 * Same reason as empdepttrnck.js: SQL Server refuses TRUNCATE TABLE on any
 * table with an identity column that's still non-empty in a way SQL Server
 * won't just let you TRUNCATE if the schema evolves a new FK onto one of
 * these later, and several of these already are FK targets in one direction
 * or another. DELETE never runs into that, and DBCC CHECKIDENT(RESEED, 0)
 * supplies the identity reset that DELETE alone doesn't do — together they
 * reproduce TRUNCATE's end state (next inserted row gets id 1 again).
 *
 * Order matters within each document type — every *Item child table is
 * deleted before its header — and Follow-up is deleted before Enquiry
 * because follow_ups.enquiry_id -> enquiries.id is NO ACTION (not CASCADE):
 * see the comment on FollowUp.enquiry in schema.prisma. Everything else
 * here links to other documents by plain text (invoice/PO/DO number), not
 * a real foreign key, so there's no other ordering constraint between the
 * groups themselves.
 */
require('dotenv').config();
const prisma = require('../prisma/client');

// One entry per table: `label` for the report, `model` is the Prisma Client
// accessor (prisma[model]), `table` is the real SQL table name (the
// @@map(...) value in schema.prisma) that DBCC CHECKIDENT needs. Order is
// the delete order — children before their own header, Follow-up before
// Enquiry — and is also the reseed order (harmless either way, but keeping
// it means "read top to bottom" tells you the whole story).
const TARGETS = [
  // --- Inventory -------------------------------------------------------
  { group: 'Inventory', label: 'Stock Receipt Items', model: 'stockReceiptItem', table: 'stock_receipt_items' },
  { group: 'Inventory', label: 'Stock Receipt', model: 'stockReceipt', table: 'stock_receipts' },
  { group: 'Inventory', label: 'Stock Issue Items', model: 'stockIssueItem', table: 'stock_issue_items' },
  { group: 'Inventory', label: 'Stock Issue', model: 'stockIssue', table: 'stock_issues' },
  { group: 'Inventory', label: 'Stock Adjustment Items', model: 'stockAdjustmentItem', table: 'stock_adjustment_items' },
  { group: 'Inventory', label: 'Stock Adjustment', model: 'stockAdjustment', table: 'stock_adjustments' },
  { group: 'Inventory', label: 'Stock Transfer Request Items', model: 'stockTransferRequestItem', table: 'stock_transfer_request_items' },
  { group: 'Inventory', label: 'Stock Transfer Request', model: 'stockTransferRequest', table: 'stock_transfer_requests' },
  { group: 'Inventory', label: 'Stock Transfer (Issue) Items', model: 'stockTransferItem', table: 'stock_transfer_items' },
  { group: 'Inventory', label: 'Stock Transfer (Issue)', model: 'stockTransfer', table: 'stock_transfers' },
  { group: 'Inventory', label: 'Stock Transfer Receipt Items', model: 'stockTransferReceiptItem', table: 'stock_transfer_receipt_items' },
  { group: 'Inventory', label: 'Stock Transfer Receipt', model: 'stockTransferReceipt', table: 'stock_transfer_receipts' },

  // --- Banking -----------------------------------------------------------
  { group: 'Banking', label: 'Deposit Entry Items', model: 'depositItem', table: 'deposit_items' },
  { group: 'Banking', label: 'Deposit Entry', model: 'bankDeposit', table: 'bank_deposits' },
  { group: 'Banking', label: 'Bank Reconciliation Transactions', model: 'bankReconciliationTransaction', table: 'bank_reconciliation_transactions' },
  { group: 'Banking', label: 'Bank Reconciliation', model: 'bankReconciliation', table: 'bank_reconciliations' },
  { group: 'Banking', label: 'Cheque Invoice Applications', model: 'chequeInvoiceApplication', table: 'cheque_invoice_applications' },
  { group: 'Banking', label: 'Cheque Print (Cheque)', model: 'cheque', table: 'cheques' },
  { group: 'Banking', label: 'Payment Receipt Applications', model: 'paymentReceiptApplication', table: 'payment_receipt_applications' },
  { group: 'Banking', label: 'Payment Receipt', model: 'paymentReceipt', table: 'payment_receipts' },
  { group: 'Banking', label: 'Payment Voucher Applications', model: 'paymentVoucherApplication', table: 'payment_voucher_applications' },
  { group: 'Banking', label: 'Payment Voucher', model: 'paymentVoucher', table: 'payment_vouchers' },

  // --- Purchase ------------------------------------------------------------
  { group: 'Purchase', label: 'Purchase Quotation Items', model: 'purchaseQuotationItem', table: 'purchase_quotation_items' },
  { group: 'Purchase', label: 'Purchase Quotation', model: 'purchaseQuotation', table: 'purchase_quotations' },
  { group: 'Purchase', label: 'Purchase Order Items', model: 'purchaseOrderItem', table: 'purchase_order_items' },
  { group: 'Purchase', label: 'Purchase Order', model: 'purchaseOrder', table: 'purchase_orders' },
  { group: 'Purchase', label: 'Purchase GRN Items', model: 'goodsReceivedNoteItem', table: 'goods_received_note_items' },
  { group: 'Purchase', label: 'Purchase GRN', model: 'goodsReceivedNote', table: 'goods_received_notes' },
  { group: 'Purchase', label: 'Purchase Return Items', model: 'purchaseReturnItem', table: 'purchase_return_items' },
  { group: 'Purchase', label: 'Purchase Return', model: 'purchaseReturn', table: 'purchase_returns' },
  { group: 'Purchase', label: 'Purchase Invoice Items', model: 'purchaseInvoiceItem', table: 'purchase_invoice_items' },
  { group: 'Purchase', label: 'Purchase Invoice', model: 'purchaseInvoice', table: 'purchase_invoices' },
  { group: 'Purchase', label: 'Purchase Credit Memo Items', model: 'purchaseCreditMemoItem', table: 'purchase_credit_memo_items' },
  { group: 'Purchase', label: 'Purchase Credit Memo', model: 'purchaseCreditMemo', table: 'purchase_credit_memos' },

  // --- Sales ---------------------------------------------------------------
  // Follow-up before Enquiry: follow_ups.enquiry_id -> enquiries.id is
  // NO ACTION, so Enquiry would fail to delete while any Follow-up still
  // points at it.
  { group: 'Sales', label: 'Follow-up', model: 'followUp', table: 'follow_ups' },
  { group: 'Sales', label: 'Enquiry', model: 'enquiry', table: 'enquiries' },
  { group: 'Sales', label: 'Sales Quotation Items', model: 'salesQuotationItem', table: 'sales_quotation_items' },
  { group: 'Sales', label: 'Sales Quotation', model: 'salesQuotation', table: 'sales_quotations' },
  { group: 'Sales', label: 'Sales Order Items', model: 'salesOrderItem', table: 'sales_order_items' },
  { group: 'Sales', label: 'Sales Order', model: 'salesOrder', table: 'sales_orders' },
  { group: 'Sales', label: 'Delivery Challan Items', model: 'deliveryChallanItem', table: 'delivery_challan_items' },
  { group: 'Sales', label: 'Delivery Challan', model: 'deliveryChallan', table: 'delivery_challans' },
  { group: 'Sales', label: 'Sales Return Items', model: 'salesReturnItem', table: 'sales_return_items' },
  { group: 'Sales', label: 'Sales Return', model: 'salesReturn', table: 'sales_returns' },
  { group: 'Sales', label: 'Sales Invoice Items', model: 'salesInvoiceItem', table: 'sales_invoice_items' },
  { group: 'Sales', label: 'Sales Invoice', model: 'salesInvoice', table: 'sales_invoices' },
  { group: 'Sales', label: 'Sales Credit Memo Items', model: 'salesCreditMemoItem', table: 'sales_credit_memo_items' },
  { group: 'Sales', label: 'Sales Credit Memo', model: 'salesCreditMemo', table: 'sales_credit_memos' },

  // --- Derived from the above (not a menu item on their own) --------------
  { group: 'Related', label: 'Stock ledger', model: 'stock', table: 'Stock' },
  { group: 'Related', label: 'Customer Outstanding', model: 'customerOutstanding', table: 'customer_outstanding' },
  { group: 'Related', label: 'Supplier Outstanding', model: 'supplierOutstanding', table: 'supplier_outstanding' },
];

// Identity reset. Kept separate from the deletes: it's the cosmetic half of
// the job, so a database where DBCC is not permitted (a restricted login)
// still gets every row deleted rather than failing the whole run.
async function reseed(table) {
  try {
    await prisma.$executeRawUnsafe(`DBCC CHECKIDENT ('[dbo].[${table}]', RESEED, 0) WITH NO_INFOMSGS`);
    return true;
  } catch (err) {
    console.warn(`  ! could not reset the identity counter on ${table}: ${err.message}`);
    return false;
  }
}

async function run() {
  const confirmed = process.argv.includes('--yes');

  // --- Dry-run counts, one table at a time -------------------------------
  // Deliberately NOT Promise.all — firing 51 count() queries at once opens
  // up to 51 simultaneous connections, which is more than this server
  // handles comfortably (see connection_limit in DATABASE_URL). Counting
  // one table, waiting for it to finish, then moving to the next keeps the
  // load on the DB down to a single query in flight at any moment.
  console.log('Inventory / Banking / Purchase / Sales — truncate all sub-menu tables');
  console.log('----------------------------------------------------------------------');
  const counts = [];
  let currentGroup = null;
  for (const t of TARGETS) {
    // eslint-disable-next-line no-await-in-loop -- intentional: see comment above.
    const c = await prisma[t.model].count();
    counts.push(c);
    if (t.group !== currentGroup) {
      currentGroup = t.group;
      console.log(`\n${currentGroup}:`);
    }
    console.log(`  ${t.label.padEnd(32)} (${t.table.padEnd(32)}) : ${c} row(s)`);
  }
  const total = counts.reduce((sum, c) => sum + c, 0);
  console.log(`\nTotal: ${total} row(s) across ${TARGETS.length} table(s)`);
  console.log('');

  if (!confirmed) {
    console.error('Nothing has been changed — this is a dry run.');
    console.error('Re-run with:  npm run truncinvbankbus -- --yes');
    process.exitCode = 1;
    return;
  }

  if (total === 0) {
    console.log('All target tables are already empty — nothing to delete.');
    return;
  }

  console.log('Deleting — one table at a time, this cannot be undone...');
  console.log('');

  // --- Delete + reseed, one table at a time, fully sequential ------------
  // No single transaction spanning all 51 tables either, for the same
  // reason as the counts above — a lighter, one-table-at-a-time footprint
  // matters more here than the all-or-nothing guarantee a giant transaction
  // would give. Each table is fully finished (deleted AND its identity
  // reset) before the next one starts, so a table is never left counted-but-
  // not-yet-cleared for long, and if the run is interrupted partway, the
  // console output above tells you exactly which table it stopped on —
  // re-running the script picks up cleanly, since every already-emptied
  // table just reports 0 rows and does nothing on its next pass.
  for (const t of TARGETS) {
    // eslint-disable-next-line no-await-in-loop -- intentional: see comment above.
    const r = await prisma[t.model].deleteMany({});
    if (r.count) console.log(`  deleted   ${r.count} row(s) from ${t.label}`);
    // eslint-disable-next-line no-await-in-loop -- intentional: see comment above.
    await reseed(t.table);
  }

  console.log('');
  console.log('Done. Every Inventory / Banking / Purchase / Sales document table (plus');
  console.log('the Stock ledger and Customer/Supplier Outstanding) is empty and its ids');
  console.log('restart at 1.');
  console.log('');
  console.log('Note: Document Numbering (Company > Document Numbering) was left alone —');
  console.log('  its series counters still continue from wherever they were.');
  console.log('Note: Collection Entry / Payment Entry (Receivables/Payables) were left');
  console.log('  alone — they are separate documents, not part of these four menus.');
}

run()
  .catch((err) => {
    console.error('Truncate error:', err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
