# Repository housekeeping.
#
# Removes files that were committed by accident and serve no purpose: the
# leftovers of an unresolved merge, editor swap files, scratch files at the
# repository root, and build output that is regenerated on every build.
#
# None of these affect behaviour — resources_*_413.js in particular is dead
# weight that has never been imported by anything — but four near-identical
# 6,000-line copies of the main route file make the codebase considerably
# harder to search, and a stray `.env` in version control is a real problem.
#
# Run from the repository root:
#     powershell -ExecutionPolicy Bypass -File .\cleanup-repo.ps1
#
# Add -WhatIf to see what would be removed without removing it:
#     powershell -ExecutionPolicy Bypass -File .\cleanup-repo.ps1 -WhatIf

[CmdletBinding(SupportsShouldProcess = $true)]
param()

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

function Remove-IfPresent {
    param([string]$RelativePath, [string]$Reason)

    $full = Join-Path $root $RelativePath
    $matches = @(Get-Item -Path $full -Force -ErrorAction SilentlyContinue)
    if (-not $matches) { return }

    foreach ($item in $matches) {
        if ($PSCmdlet.ShouldProcess($item.FullName, "Remove ($Reason)")) {
            Remove-Item -Path $item.FullName -Force -Recurse -ErrorAction SilentlyContinue
            Write-Host ("  removed  {0}" -f $item.FullName.Substring($root.Length + 1))
        }
    }
}

Write-Host "Merge-conflict leftovers (never imported by anything)"
Remove-IfPresent 'backend\src\routes\resources_BACKUP_413.js' 'merge leftover'
Remove-IfPresent 'backend\src\routes\resources_BASE_413.js'   'merge leftover'
Remove-IfPresent 'backend\src\routes\resources_LOCAL_413.js'  'merge leftover'
Remove-IfPresent 'backend\src\routes\resources_REMOTE_413.js' 'merge leftover'

Write-Host "`nEditor swap files"
Remove-IfPresent 'backend\src\routes\.resources*.swp' 'vim swap file'

Write-Host "`nScratch files at the repository root"
Remove-IfPresent 'q'        'scratch file'
Remove-IfPresent 'adasads'  'scratch file'

Write-Host "`nBuild logs and generated output"
Remove-IfPresent 'frontend\build*.log'                  'build log'
Remove-IfPresent 'frontend\err.txt'                     'build log'
Remove-IfPresent 'frontend\out_grn.js'                  'scratch output'
Remove-IfPresent 'frontend\out_schema.js'               'scratch output'
Remove-IfPresent 'frontend\vite.config.js.timestamp-*'  'vite temp config'
Remove-IfPresent 'frontend\dist'                        'build output (regenerated by npm run build)'

Write-Host "`n--------------------------------------------------------------"
Write-Host "Now untrack the files that should never have been committed."
Write-Host "These stay on disk; they are only removed from version control:"
Write-Host ""
Write-Host "    git rm --cached backend/.env"
Write-Host "    git rm -r --cached frontend/dist"
Write-Host "    git commit -m 'Remove committed secrets and build output'"
Write-Host ""
Write-Host "Then ROTATE the credentials that were exposed in backend/.env:"
Write-Host "  - both JWT secrets (they are still the shipped placeholders)"
Write-Host "  - the Azure PostgreSQL password"
Write-Host ""
Write-Host "Generate a new JWT secret with:"
Write-Host "    node -e ""console.log(require('crypto').randomBytes(48).toString('base64url'))"""
Write-Host "--------------------------------------------------------------"
