// One CRUD hook-set per resource, generated from the shared factory.
// Import from here in pages instead of writing bespoke RTK Query code.
import { useMemo } from 'react';
import { partnerAddressLines } from '../lib/addressFormat';
import { createCrudApi } from '../lib/createCrudApi';
import { baseApi } from '../store/baseApi';

// Company Setup
export const branchApi = createCrudApi({ resourcePath: 'company/branches', tagType: 'Branch', keepUnusedDataFor: 300 });
export const financialYearApi = createCrudApi({ resourcePath: 'company/financial-years', tagType: 'FinancialYear', keepUnusedDataFor: 300 });
export const taxCodeApi = createCrudApi({ resourcePath: 'company/tax-codes', tagType: 'TaxCode', keepUnusedDataFor: 300 });
export const bankNameApi = createCrudApi({ resourcePath: 'company/bank-names', tagType: 'BankName', keepUnusedDataFor: 300 });
export const houseBankApi = createCrudApi({ resourcePath: 'company/house-banks', tagType: 'HouseBank', keepUnusedDataFor: 300 });
export const salesEmployeeApi = createCrudApi({ resourcePath: 'company/sales-employees', tagType: 'SalesEmployee', keepUnusedDataFor: 300 });

// Employee Master's bulk import has no RTK Query endpoints of its own: it
// goes through the shared BulkImportDialog, which deliberately uses a plain
// authenticated fetch against URL strings so one dialog can serve every
// resource without knowing any of their cache tags (see that component's own
// doc comment). Refreshing the list after an import is the calling page's
// job via `onImported` — SalesEmployee.jsx passes its list query's refetch.

export const approvalFlowApi = createCrudApi({ resourcePath: 'company/approval-flows', tagType: 'ApprovalFlow' });
// Department Master — backs Employee Master's Department dropdown (by id).
export const departmentMasterApi = createCrudApi({ resourcePath: 'department-master', tagType: 'DepartmentMaster', keepUnusedDataFor: 300 });

// Accounting
export const accountGroupApi = createCrudApi({ resourcePath: 'account-groups', tagType: 'AccountGroup', keepUnusedDataFor: 300 });
export const accountTypeApi = createCrudApi({ resourcePath: 'account-types', tagType: 'AccountType', keepUnusedDataFor: 300 });
// Same "rarely changes, read on nearly every accounting screen" bucket as
// Account Group/Account Type just above — kept at the RTK Query default
// (60s) before, unlike its siblings, even though every Journal Entry line,
// GL posting screen and report dropdown re-fetches it constantly.
export const chartOfAccountApi = createCrudApi({ resourcePath: 'chart-of-accounts', tagType: 'ChartOfAccount', keepUnusedDataFor: 300 });

// Bulk "Import from Excel" + "Download Template" for Chart of Accounts, the
// same hand-injected shape as Opening Balance's import above: the import is
// a multipart upload (`body: formData` lets fetchBaseQuery skip
// JSON.stringify-ing it and leave the multipart Content-Type/boundary to the
// browser), and the template is a server-generated binary file, not JSON, so
// its query overrides `responseHandler` to hand back a Blob instead of
// letting fetchBaseQuery try to parse it as JSON. Both are mutations rather
// than queries — nothing here is cached data to read, each is a one-off
// action triggered by a button click.
const chartOfAccountImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importChartOfAccountsXlsx: builder.mutation({
      query: (formData) => ({ url: '/chart-of-accounts/import-xlsx', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'ChartOfAccount', id: 'LIST' }],
    }),
    downloadChartOfAccountsTemplate: builder.mutation({
      query: () => ({
        url: '/chart-of-accounts/import-template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportChartOfAccountsXlsxMutation = chartOfAccountImportApi.useImportChartOfAccountsXlsxMutation;
export const useDownloadChartOfAccountsTemplateMutation = chartOfAccountImportApi.useDownloadChartOfAccountsTemplateMutation;

export const glAccountDeterminationApi = createCrudApi({ resourcePath: 'gl-account-determinations', tagType: 'GlAccountDetermination' });
export const journalEntryApi = createCrudApi({ resourcePath: 'journal-entries', tagType: 'JournalEntry' });

// "Post to G/L" — settle a journal entry parked as 'Pending G/L' because
// account determination was incomplete when its source document posted.
// Hand-injected rather than generated by createCrudApi: it acts on an
// existing record and sends no body, which is neither of that factory's
// mutation shapes.
const journalEntryPostApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    postJournalEntryToGl: builder.mutation({
      query: (id) => ({ url: `/journal-entries/${id}/post-to-gl`, method: 'POST' }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, id) => [
        { type: 'JournalEntry', id },
        { type: 'JournalEntry', id: 'LIST' },
      ],
    }),
  }),
  overrideExisting: false,
});
export const usePostJournalEntryToGlMutation = journalEntryPostApi.usePostJournalEntryToGlMutation;

// Product Setup
export const productGroupApi = createCrudApi({ resourcePath: 'product-groups', tagType: 'ProductGroup', keepUnusedDataFor: 300 });
export const productSubGroupApi = createCrudApi({ resourcePath: 'product-sub-groups', tagType: 'ProductSubGroup', keepUnusedDataFor: 300 });
export const brandApi = createCrudApi({ resourcePath: 'brands', tagType: 'Brand', keepUnusedDataFor: 300 });
export const uomApi = createCrudApi({ resourcePath: 'uoms', tagType: 'Uom', keepUnusedDataFor: 300  });
export const currencyApi = createCrudApi({ resourcePath: 'currencies', tagType: 'Currency', keepUnusedDataFor: 300 });
export const hsnMasterApi = createCrudApi({ resourcePath: 'hsn-master', tagType: 'HsnMaster', keepUnusedDataFor: 300 });
export const invoiceTypeApi = createCrudApi({ resourcePath: 'invoice-types', tagType: 'InvoiceType', keepUnusedDataFor: 300 });
export const productApi = createCrudApi({ resourcePath: 'products', tagType: 'Product', keepUnusedDataFor: 300 });

// Live current stock per product (openingStock plus every posted Stock
// Receipt/Issue/Adjustment movement) — separate from the CRUD product record
// since it's computed, not stored. Tagged 'Product' so it refetches whenever
// a product or stock-movement mutation invalidates the product list.
const productStockApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getProductCurrentStock: builder.query({
      query: () => '/products/current-stock',
      transformResponse: (response) => response.data,
      keepUnusedDataFor: 300,
      providesTags: [{ type: 'Product', id: 'CURRENT_STOCK' }],
    }),
  }),
  overrideExisting: false,
});
export const useGetProductCurrentStockQuery = productStockApi.useGetProductCurrentStockQuery;

// Phase 4 of the data-loading performance work (pure data-access, no
// business-logic change) — one combined round-trip for the five FAST
// dropdown lookups Product Master's Add/Edit form needs (see the route's
// own comment in backend/src/routes/resources.js for exactly what's in it
// and why Tax Code is left out). `keepUnusedDataFor` matches the 300s every
// other Product Setup master list already uses above, since these are the
// same "rarely changes" master lists, just fetched together.
//
// HSN Master and Price List were originally folded into this endpoint too
// (all eight but Tax Code), then pulled back out after measurement showed
// the combined call taking ~9.8s / 5.4MB — the fast fields ended up waiting
// on the slowest one instead of loading instantly the way they did before
// Phase 4. They're back to their own separate, `skip`-gated calls below
// (`hsnMasterApi.useList`, `priceListApi.useList`, both already defined
// above) — exactly their pre-Phase-4 behaviour — so their `providesTags`
// entries are removed from here since this endpoint's response no longer
// carries that data.
const productFormLookupsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getProductFormLookups: builder.query({
      query: () => '/products/form-lookups',
      transformResponse: (response) => response.data,
      keepUnusedDataFor: 300,
      providesTags: [
        { type: 'ProductGroup', id: 'LIST' },
        { type: 'ProductSubGroup', id: 'LIST' },
        { type: 'Brand', id: 'LIST' },
        { type: 'Uom', id: 'LIST' },
        { type: 'BusinessPartner', id: 'LIST' },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetProductFormLookupsQuery = productFormLookupsApi.useGetProductFormLookupsQuery;

// Product Master > Inventory tab — the per-warehouse position for one product.
// Its own endpoint rather than fields on the product record because everything
// it shows except the Min/Max levels is derived from stock movements and open
// orders at read time (see backend utils/productInventory.js).
//
// Tagged per product code, so saving one product's levels refetches that
// product's inventory and leaves every other cached product alone.
const productInventoryApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getProductInventory: builder.query({
      query: (productCode) => `/products/${encodeURIComponent(productCode)}/inventory`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, productCode) => [
        { type: 'Product', id: `INVENTORY_${productCode}` },
      ],
    }),
    // saveProductInventory (PUT .../inventory) removed along with Min/Max
    // Inventory Level — see migration
    // 20260823210000_drop_product_warehouse_levels. The tab is now read-only.
  }),
  overrideExisting: false,
});
export const useGetProductInventoryQuery = productInventoryApi.useGetProductInventoryQuery;

// Live on-hand quantity for one (productCode, warehouse) pair — backs
// lib/useWarehouseStock.js's "Available: N" inline hint on every
// stock-reducing line-item table (Sales Order, Delivery Challan, Sales
// Invoice, Stock Issue, a Decrease Stock Adjustment line). Wraps
// GET /products/:productCode/stock?warehouse=... (see backend
// routes/resources.js), a lightweight single-pair lookup — not the heavier
// all-warehouses '/products/:productCode/inventory' endpoint above — since
// this is re-run on effectively every warehouse/quantity keystroke across
// many tables at once.
//
// Not cached against a tag: on-hand quantity changes with every other
// document's own save (a different Sales Order consuming the same
// product/warehouse), not just this hook's own mutations, so there's no
// single invalidation that would keep a tag-based cache correct — the
// caller re-queries per keystroke instead (see useWarehouseStock.js).
const productWarehouseStockApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getProductWarehouseStock: builder.query({
      query: ({ productCode, warehouse }) => ({
        url: `/products/${encodeURIComponent(productCode)}/stock`,
        params: { warehouse: warehouse || '' },
      }),
      transformResponse: (response) => response.data,
      providesTags: (result, error, { productCode, warehouse } = {}) => [
        // Only the specific (product, warehouse) tag. The bare 'Product' tag
        // this used to also provide was pure redundancy: a bare invalidation
        // (STOCK_MOVING_TAGS, see below) already reaches every id under the
        // 'Product' type, this entry's STOCK_<code>_<warehouse> id included,
        // so every document save still refreshes a visible "Available: N".
        { type: 'Product', id: `STOCK_${productCode}_${warehouse}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetProductWarehouseStockQuery = productWarehouseStockApi.useGetProductWarehouseStockQuery;

// Business Partner form > summary totals shown below Account Balance —
// Deliveries/Orders for a Customer, Goods Receipt POs/Purchase Orders for a
// Vendor. Computed server-side from the partner's actual documents (see
// backend routes/resources.js GET /business-partners/:code/summary), so this
// is a plain read query keyed by partner code rather than data submitted
// with the form.
const businessPartnerSummaryApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getBusinessPartnerSummary: builder.query({
      query: (code) => `/business-partners/${encodeURIComponent(code)}/summary`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, code) => [
        { type: 'BusinessPartner', id: `SUMMARY_${code}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetBusinessPartnerSummaryQuery = businessPartnerSummaryApi.useGetBusinessPartnerSummaryQuery;

// Sales/Purchase Invoice list behind the view icon next to Account Balance
// on the Business Partner form — same partner/code as the summary above,
// just the line items instead of the aggregate (see backend routes/
// resources.js GET /business-partners/:code/invoices). Callers skip this
// until the dialog is actually opened (see InvoiceListDialog usage in
// BusinessPartner.jsx) so it's never fetched just for loading the form.
const businessPartnerInvoicesApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getBusinessPartnerInvoices: builder.query({
      query: (code) => `/business-partners/${encodeURIComponent(code)}/invoices`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, code) => [
        { type: 'BusinessPartner', id: `INVOICES_${code}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetBusinessPartnerInvoicesQuery = businessPartnerInvoicesApi.useGetBusinessPartnerInvoicesQuery;

// Document list behind the view icon next to Deliveries/Orders/Purchase
// Orders/Goods Receipt POs on the Business Partner form — one query for all
// four tiles, distinguished by `type` (see backend routes/resources.js GET
// /business-partners/:code/documents and its BP_SUMMARY_DOCUMENT_TYPES map).
// Callers skip this until the dialog is actually opened (see
// BusinessPartnerDocumentDialog usage in BusinessPartner.jsx).
const businessPartnerDocumentsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getBusinessPartnerDocuments: builder.query({
      query: ({ code, type }) => `/business-partners/${encodeURIComponent(code)}/documents?type=${encodeURIComponent(type)}`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, { code, type }) => [
        { type: 'BusinessPartner', id: `DOCS_${code}_${type}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetBusinessPartnerDocumentsQuery = businessPartnerDocumentsApi.useGetBusinessPartnerDocumentsQuery;

// Machineries for ONE Business Partner — the "Machineries" tab's grid on
// that partner's own record (see BusinessPartnerMachinery), read here so
// MachineryCodeSelect on a Sales document can offer only the machineries
// that belong to whichever Customer is currently selected on that document.
// Skipped entirely (no request) until a business partner id is actually
// known — see MachineryCodeSelect's use of `skip`.
const businessPartnerMachineriesApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getBusinessPartnerMachineries: builder.query({
      query: (businessPartnerId) => `/business-partners/${encodeURIComponent(businessPartnerId)}/machineries`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, businessPartnerId) => [
        { type: 'BusinessPartner', id: `MACHINERIES_${businessPartnerId}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetBusinessPartnerMachineriesQuery = businessPartnerMachineriesApi.useGetBusinessPartnerMachineriesQuery;

// Which of a product's three flow flags (Sales / Purchase / Inventory Item)
// are pinned by documents that already use it, so Product Master can render
// those checkboxes disabled and say what is holding them.
//
// Tagged per product code alongside that product's other cached reads, so
// saving a document that uses the product does not leave a stale "not used
// anywhere" answer behind — the flags can only ever become MORE locked, and a
// stale unlocked answer is one the server would reject on save anyway.
const productUsageApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getProductUsage: builder.query({
      query: (productCode) => `/products/${encodeURIComponent(productCode)}/usage`,
      transformResponse: (response) => response.data,
      providesTags: (result, error, productCode) => [
        { type: 'Product', id: `USAGE_${productCode}` },
      ],
    }),
  }),
  overrideExisting: false,
});
export const useGetProductUsageQuery = productUsageApi.useGetProductUsageQuery;

// Batch/Serial stock still available to pick from — feeds the "Batches
// Number - Selection" / "Serial Numbers - Selection" dialog on Delivery
// Challan and Stock Issue lines (BatchSerialSelectionDialog.jsx). Not cached
// against a tag: `refetchOnMountOrArgChange` forces a fresh read every time
// the dialog opens, since the pool of what's available changes on every
// other save of any issue-type document, not just this one's own mutations.
const batchSerialAvailabilityApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getAvailableBatches: builder.query({
      query: ({ productCode, warehouse }) => {
        const params = new URLSearchParams({ productCode: productCode || '', available: 'true' });
        if (warehouse) params.set('warehouse', warehouse);
        return `/product-batches?${params.toString()}`;
      },
      transformResponse: (response) => response.data,
    }),
    getAvailableSerials: builder.query({
      query: ({ productCode, warehouse }) => {
        const params = new URLSearchParams({ productCode: productCode || '', status: 'In Stock' });
        if (warehouse) params.set('warehouse', warehouse);
        return `/product-serials?${params.toString()}`;
      },
      transformResponse: (response) => response.data,
    }),
    // Batch/Serial stock currently OUT with a customer — feeds
    // BatchSerialRestockDialog.jsx on Sales Return / Sales Credit Memo lines.
    // Batches have no per-row "issued" status (unlike serials): any batch of
    // the product is a valid restock target, so this omits the
    // `available=true` filter that narrows the Selection dialog's pool to
    // what still has quantity on it. Serials are scoped to `status=Issued` —
    // the restockable pool is the mirror image of `status=In Stock` above.
    getRestockableBatches: builder.query({
      query: ({ productCode, warehouse }) => {
        const params = new URLSearchParams({ productCode: productCode || '' });
        if (warehouse) params.set('warehouse', warehouse);
        return `/product-batches?${params.toString()}`;
      },
      transformResponse: (response) => response.data,
    }),
    getRestockableSerials: builder.query({
      query: ({ productCode, warehouse }) => {
        const params = new URLSearchParams({ productCode: productCode || '', status: 'Issued' });
        if (warehouse) params.set('warehouse', warehouse);
        return `/product-serials?${params.toString()}`;
      },
      transformResponse: (response) => response.data,
    }),
  }),
  overrideExisting: false,
});
export const useGetAvailableBatchesQuery = batchSerialAvailabilityApi.useGetAvailableBatchesQuery;
export const useGetAvailableSerialsQuery = batchSerialAvailabilityApi.useGetAvailableSerialsQuery;
export const useGetRestockableBatchesQuery = batchSerialAvailabilityApi.useGetRestockableBatchesQuery;
export const useGetRestockableSerialsQuery = batchSerialAvailabilityApi.useGetRestockableSerialsQuery;

export const purchasePriceApi = createCrudApi({ resourcePath: 'purchase-prices', tagType: 'PurchasePrice' });
export const salesPriceApi = createCrudApi({ resourcePath: 'sales-prices', tagType: 'SalesPrice' });
export const customerDiscountApi = createCrudApi({ resourcePath: 'customer-discounts', tagType: 'CustomerDiscount' });

export const priceListApi = createCrudApi({ resourcePath: 'price-lists', tagType: 'PriceList' });

// Price List's own "Download Excel" (whatever's currently in the item
// table), "Download Template" and "Upload Price List" — same hand-injected
// shape as Chart of Accounts' import pair above, except the upload here
// doesn't write to the database (Price List is saved as a whole via the
// normal create/update above): it just parses the sheet and hands rows back
// for the item table to adopt, and the "download" endpoints both return a
// server-generated .xlsx Blob rather than JSON.
const priceListImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    parsePriceListXlsx: builder.mutation({
      query: (formData) => ({ url: '/price-lists/parse-xlsx', method: 'POST', body: formData }),
    }),
    downloadPriceListTemplate: builder.mutation({
      query: () => ({
        url: '/price-lists/import-template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
    exportPriceListXlsx: builder.mutation({
      query: (items) => ({
        url: '/price-lists/export-xlsx',
        method: 'POST',
        body: { items },
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useParsePriceListXlsxMutation = priceListImportApi.useParsePriceListXlsxMutation;
export const useDownloadPriceListTemplateMutation = priceListImportApi.useDownloadPriceListTemplateMutation;

// Auto-fill source for Purchase (DLP) / Sales (CLP) Unit Price lookups —
// see usePriceListRates. Tagged 'PriceList' so saving/activating a price
// list (via priceListApi above) invalidates it on next mount.
const priceListActiveRatesApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getActivePriceListRates: builder.query({
      query: (type) => ({ url: `/price-lists/active/${type}`, method: 'GET' }),
      providesTags: [{ type: 'PriceList', id: 'ACTIVE_RATES' }],
    }),
  }),
  overrideExisting: false,
});
export const useGetActivePriceListRatesQuery = priceListActiveRatesApi.useGetActivePriceListRatesQuery;
export const useExportPriceListXlsxMutation = priceListImportApi.useExportPriceListXlsxMutation;

// Business Partner
// Transporter master — a small, rarely-changed dropdown source (Delivery
// Challan, GRN), same 300s bucket as the other masters above.
export const transportApi = createCrudApi({ resourcePath: 'transporters', tagType: 'Transport', keepUnusedDataFor: 300 });
// Unified partner master — a master/detail resource (see routes/resources.js),
// but its GET/POST/PUT/DELETE shape mirrors the generic CRUD routes exactly,
// so the same createCrudApi hook-set works against it unmodified.
export const businessPartnerApi = createCrudApi({
  resourcePath: 'business-partners',
  tagType: 'BusinessPartner',
  keepUnusedDataFor: 300,
  // Saving a Business Partner (create/update) can add/edit rows on its
  // "Machineries" tab, but that data is read through a separate query
  // (getBusinessPartnerMachineries, tagged BusinessPartner/MACHINERIES_<id>)
  // that this generic CRUD update/create never otherwise touches — without
  // this, the Machine Serial No. dropdown on sales documents keeps showing
  // stale/cached machineries after they're edited on the partner record.
  extraInvalidateTags: (result, error, arg) => {
    const id = result?.id ?? arg?.id;
    return id != null ? [{ type: 'BusinessPartner', id: `MACHINERIES_${id}` }] : [];
  },
});

// Customer Master / Supplier Master were retired in favor of Business
// Partner (filtered by partnerType Customer/Vendor) — see BUGLOG. Every page
// that used to read customerApi/supplierApi only ever called `.useList()`
// with no arguments to populate a dropdown or a lookup map, so rather than
// touch each of those ~45 call sites individually, customerApi/supplierApi
// are kept as adapters: same `.useList()` shape, backed by
// GET /business-partners?partnerType=..., with each row's fields aliased
// back to the old Customer/Supplier field names (customerCode/customerName,
// supplierCode/supplierName, phone, ...) alongside the native Business
// Partner ones. Fields the old masters had that Business Partner does not
// (discount %, price list, GSTIN/PAN, city/state, supplier bank details,
// customer/supplier "group") are NOT aliased — callers that read those now
// get undefined, by design (see the field-gap audit in BUGLOG).
//
// create/update/delete are deliberately not exposed here — Customer Master/
// Supplier Master are gone, so nothing outside this adapter should be
// writing through the old shape; Business Partner's own page is the only
// place these records are created or edited now.
function formatLegacyPartnerAddress(addr) {
  if (!addr) return '';
  // addressName (the Business Partner Address tab's own "Address Name *"
  // field) was missing from this line entirely -- every page-local
  // formatBusinessPartnerAddress (Sales Order/Invoice/Quotation/Credit
  // Memo/Return, Delivery Challan, Purchase Order/GRN/Credit Memo) leads
  // with it, but this shared adapter (what customerApi/supplierApi's
  // .billingAddress/.shippingAddress actually come from -- see
  // toLegacyPartnerShape below) silently dropped it. That's what "ship to a
  // different customer" picks its address from, so the customer's own
  // Billing/Shipping Address name never made it into the document.
  // Standard order (lib/addressFormat.js), no double commas.
  return partnerAddressLines(addr).join('\n');
}

function toLegacyPartnerShape(p) {
  // Sales/Purchase forms (Sales Quotation, Sales Order, Sales Invoice,
  // Delivery Challan, Enquiry, Purchase Order/Quotation, ...) all auto-fill
  // their own Contact Person/Phone/Email fields from whatever this adapter
  // hands back for a picked customer/vendor. When the partner has a Contact
  // Person marked "Set as default" on the Business Partner form, that
  // person's own details are what should land there — not just the
  // partner's own top-level phone/email, which is what "the first contact"
  // effectively meant before isDefault existed.
  //
  // Falls back to the first contact row when none is marked default: a
  // partner with exactly one contact is the common case, and nothing forces
  // that lone row to be explicitly flagged "Default" — without this fallback
  // it (and every document's Contact Person auto-fill) silently stayed blank
  // even though the contact was right there.
  const defaultContact = Array.isArray(p.contacts) && p.contacts.length
    ? (p.contacts.find((c) => c.isDefault) || p.contacts[0])
    : null;
  const defaultContactName = defaultContact
    ? [defaultContact.firstName, defaultContact.lastName].filter(Boolean).join(' ')
    : '';

  const billingAddr = Array.isArray(p.addresses)
    ? (p.addresses.find((a) => a.addressType === 'Billing' && a.isDefault)
       || p.addresses.find((a) => a.addressType === 'Billing')
       || p.addresses.find((a) => a.isDefault)
       || p.addresses[0])
    : null;
  const shippingAddr = Array.isArray(p.addresses)
    ? (p.addresses.find((a) => a.addressType === 'Shipping' && a.isDefault)
       || p.addresses.find((a) => a.addressType === 'Shipping')
       || billingAddr)
    : null;

  const gstin = billingAddr?.gstNumber || shippingAddr?.gstNumber || p.gstin || p.gstNumber || '';
  const gstRegistrationType = billingAddr?.gstType || shippingAddr?.gstType || p.gstRegistrationType || p.gstType || 'Regular/TDS/ISD';

  return {
    ...p,
    customerCode: p.partnerCode,
    customerName: p.partnerName,
    supplierCode: p.partnerCode,
    supplierName: p.partnerName,
    phone: defaultContact?.mobile || defaultContact?.telephone || p.mobile || p.telephone || '',
    email: defaultContact?.email || p.email || '',
    contactPerson: p.contactPerson || defaultContactName,
    notes: p.remarks || '',
    // Business Partner's currency is "which currencies this partner deals
    // in" (BP_CURRENCY_OPTIONS: All/INR/USD/EUR/GBP, default 'All') — a
    // different thing from a document's own currency code. Several sales/
    // purchase forms do `setValue('currency', found.currency || 'INR')` when
    // a customer/supplier is picked, expecting a real code or nothing; 'All'
    // would pass that `||` (it's truthy) and get written onto the document
    // as an invalid currency. Only forward it when it names an actual
    // currency, so the existing fallback to 'INR' still applies otherwise.
    currency: p.currency && p.currency !== 'All' ? p.currency : undefined,
    billingAddress: p.billingAddress || formatLegacyPartnerAddress(billingAddr),
    shippingAddress: p.shippingAddress || formatLegacyPartnerAddress(shippingAddr),
    state: p.state || billingAddr?.state || shippingAddr?.state || '',
    city: p.city || billingAddr?.city || shippingAddr?.city || '',
    gstin,
    gstNumber: gstin,
    gstRegistrationType,
    gstType: gstRegistrationType,
  };
}

function makeLegacyPartnerApi(partnerType) {
  return {
    // Defaults to the server's slim `?view=picker` projection (id/code/name/
    // mobile/telephone/email/contactPerson/remarks/currency/status/
    // paymentTerms + a trimmed contacts/addresses select — see
    // businessPartnerPickerSelect in backend/src/routes/resources.js,
    // audited field-by-field against every customerApi/supplierApi
    // consumer). A caller passing its own `view` (or `undefined` to force
    // the full row) still wins — `params` is spread after `view` on purpose.
    useList: (params) => {
      const query = { view: 'picker', ...(params || {}), partnerType };
      const result = businessPartnerApi.useList(query);
      const data = useMemo(
        () => (result.data ? result.data.map(toLegacyPartnerShape) : result.data),
        [result.data]
      );
      return { ...result, data };
    },
  };
}
export const customerApi = makeLegacyPartnerApi('Customer');
export const supplierApi = makeLegacyPartnerApi('Vendor');

// Peek-only — the "Code" field's Auto - Customer/Auto - Supplier modes call
// this as soon as they're picked, to show the number that will be assigned
// on save before the record is actually created. Mirrors
// usePeekDocumentNumberMutation's own shape (a POST mutation used purely to
// get an imperative trigger fn, not because it writes anything).
const businessPartnerCodeApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    peekBusinessPartnerCode: builder.mutation({
      query: (body) => ({ url: '/business-partners/next-code', method: 'POST', body }),
      transformResponse: (response) => response.data,
    }),
  }),
  overrideExisting: false,
});
export const usePeekBusinessPartnerCodeMutation = businessPartnerCodeApi.usePeekBusinessPartnerCodeMutation;

// Logo upload/remove — separate multipart/DELETE endpoints from the plain
// create/update above, since the object goes to OCI Object Storage rather
// than into the JSON body (same shape as useUploadCompanyLogoMutation /
// useRemoveCompanyLogoMutation in features/company/companyDetailsApi.js).
// `formData` is a FormData with a single 'file' field; fetchBaseQuery
// leaves FormData bodies alone so the browser sets its own multipart
// boundary. Both invalidate this partner's own id tag (and the list, since
// the list route now also returns each row's logoUrl) so every subscriber
// refetches and picks up the new/removed logo automatically.
const businessPartnerLogoApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    uploadBusinessPartnerLogo: builder.mutation({
      query: ({ id, formData }) => ({ url: `/business-partners/${id}/logo`, method: 'POST', body: formData }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'BusinessPartner', id }, { type: 'BusinessPartner', id: 'LIST' }],
    }),
    removeBusinessPartnerLogo: builder.mutation({
      query: (id) => ({ url: `/business-partners/${id}/logo`, method: 'DELETE' }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, id) => [{ type: 'BusinessPartner', id }, { type: 'BusinessPartner', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useUploadBusinessPartnerLogoMutation = businessPartnerLogoApi.useUploadBusinessPartnerLogoMutation;
export const useRemoveBusinessPartnerLogoMutation = businessPartnerLogoApi.useRemoveBusinessPartnerLogoMutation;

// House Bank QR code upload/remove — same multipart/DELETE pattern as
// businessPartnerLogoApi above, backed by House Bank's own
// POST/DELETE /company/house-banks/:id/qr-code endpoints. `formData` is a
// FormData with a single 'file' field. Both invalidate this bank's own id
// tag (and the list, since the list route also returns each row's
// qrCodeUrl) so every subscriber refetches and picks up the new/removed QR
// code automatically.
const houseBankQrCodeApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    uploadHouseBankQrCode: builder.mutation({
      query: ({ id, formData }) => ({ url: `/company/house-banks/${id}/qr-code`, method: 'POST', body: formData }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'HouseBank', id }, { type: 'HouseBank', id: 'LIST' }],
    }),
    removeHouseBankQrCode: builder.mutation({
      query: (id) => ({ url: `/company/house-banks/${id}/qr-code`, method: 'DELETE' }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, id) => [{ type: 'HouseBank', id }, { type: 'HouseBank', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useUploadHouseBankQrCodeMutation = houseBankQrCodeApi.useUploadHouseBankQrCodeMutation;
export const useRemoveHouseBankQrCodeMutation = houseBankQrCodeApi.useRemoveHouseBankQrCodeMutation;

// Sales Employee signature upload/remove — same multipart/DELETE pattern as
// businessPartnerLogoApi / houseBankQrCodeApi above, backed by Sales
// Employee's own POST/DELETE /company/sales-employees/:id/signature routes.
// `formData` is a FormData with a single 'file' field. Both invalidate this
// employee's own id tag (and the list, since the list route's `annotate`
// hook attaches each row's signatureUrl too) so every subscriber refetches
// and picks up the new/removed signature automatically.
const employeeSignatureApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    uploadEmployeeSignature: builder.mutation({
      query: ({ id, formData }) => ({ url: `/company/sales-employees/${id}/signature`, method: 'POST', body: formData }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'SalesEmployee', id }, { type: 'SalesEmployee', id: 'LIST' }],
    }),
    removeEmployeeSignature: builder.mutation({
      query: (id) => ({ url: `/company/sales-employees/${id}/signature`, method: 'DELETE' }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, id) => [{ type: 'SalesEmployee', id }, { type: 'SalesEmployee', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useUploadEmployeeSignatureMutation = employeeSignatureApi.useUploadEmployeeSignatureMutation;
export const useRemoveEmployeeSignatureMutation = employeeSignatureApi.useRemoveEmployeeSignatureMutation;

export const warehouseApi = createCrudApi({ resourcePath: 'warehouses', tagType: 'Warehouse', keepUnusedDataFor: 300 });
export const locationApi  = createCrudApi({ resourcePath: 'locations',  tagType: 'Location', keepUnusedDataFor: 300 });

// Rich Warehouse/Location masters imported from Master Data.xlsx — separate
// from warehouseApi/locationApi above (see the model comments in
// schema.prisma). warehouseMasterApi backs Opening Balance's Warehouse
// dropdown.
export const warehouseMasterApi = createCrudApi({ resourcePath: 'warehouse-master', tagType: 'WarehouseMaster', keepUnusedDataFor: 300 });

// Unscoped (all branches) Active-warehouse lookup, for the destination side of
// a Branch Transfer request -- warehouseMasterApi's list is limited to the
// caller's own branches for non-admins. See the backend route's comment.
const warehouseTransferLookupApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getTransferWarehouses: builder.query({
      query: () => ({ url: '/warehouse-master/transfer-lookup' }),
      transformResponse: (response) => response.data,
      providesTags: [{ type: 'WarehouseMaster', id: 'LIST' }],
      keepUnusedDataFor: 300,
    }),
  }),
  overrideExisting: false,
});
export const useGetTransferWarehousesQuery = warehouseTransferLookupApi.useGetTransferWarehousesQuery;

// Chart Of Accounts: live ledger movement (posted debit/credit) per account code.
// Re-read on every mount of the page (see ChartOfAccounts.jsx) since any posted
// document changes it.
const chartOfAccountBalanceApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getChartOfAccountBalances: builder.query({
      query: () => ({ url: '/chart-of-accounts/balances' }),
      transformResponse: (response) => response.data,
      keepUnusedDataFor: 30,
      // Anything that posts to (or reverses from) the ledger invalidates
      // 'JournalEntry' -- BP/Inventory Opening Balance, Journal Entry and
      // its G/L re-post -- so the Balance refreshes without a page reload.
      providesTags: ['JournalEntry', { type: 'JournalEntry', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useGetChartOfAccountBalancesQuery = chartOfAccountBalanceApi.useGetChartOfAccountBalancesQuery;
export const locationMasterApi  = createCrudApi({ resourcePath: 'location-master',  tagType: 'LocationMaster', keepUnusedDataFor: 300 });
// 'Product' among the invalidated tags: an opening balance IS part of a
// product's current stock (see getOpeningBalanceMovements in
// backend/src/utils/stockLedger.js), so keying one has to refresh Product
// Master's Stock column and Inventory tab the same way a Stock Receipt does.
// Declared inline rather than via STOCK_MOVING_TAGS below, which is defined
// further down this file and would still be in its temporal dead zone here.
// 'JournalEntry' too: each Inventory Opening Balance document posts a journal
// entry (Dr Inventory / Cr Opening Balance Account), so saving, editing or
// deleting a line changes the ledger and the Chart Of Accounts Balance.
export const openingBalanceApi  = createCrudApi({ resourcePath: 'opening-balance',  tagType: 'OpeningBalance', extraInvalidateTags: ['Product', 'JournalEntry'] });

// Bulk "Import from Excel" for Opening Balance — a multipart upload rather
// than the generic create/update JSON shape, so it's hand-injected here
// instead of coming from createCrudApi. `body: formData` is passed straight
// through: fetchBaseQuery skips JSON.stringify-ing FormData and lets the
// browser set the multipart Content-Type/boundary itself.
const openingBalanceImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importOpeningBalanceXlsx: builder.mutation({
      query: (formData) => ({ url: '/opening-balance/import-xlsx', method: 'POST', body: formData }),
      // 'Product' for the same reason as openingBalanceApi above — a bulk
      // import moves every imported product's stock figure.
      invalidatesTags: [{ type: 'OpeningBalance', id: 'LIST' }, 'Product', 'JournalEntry'],
    }),
    // Header + item lines saved together. Each line is upserted on
    // (itemCode, warehouse) server-side, so this both creates and updates —
    // hence the same invalidations as a bulk import.
    saveOpeningBalanceBatch: builder.mutation({
      query: (body) => ({ url: '/opening-balance/batch', method: 'POST', body }),
      invalidatesTags: [{ type: 'OpeningBalance', id: 'LIST' }, 'Product', 'JournalEntry'],
    }),
  }),
  overrideExisting: false,
});
export const useImportOpeningBalanceXlsxMutation = openingBalanceImportApi.useImportOpeningBalanceXlsxMutation;
export const useSaveOpeningBalanceBatchMutation = openingBalanceImportApi.useSaveOpeningBalanceBatchMutation;

// Saving any document that moves stock changes every derived product figure —
// Product Master's "Stock" column (GET /products/current-stock) and its
// Inventory tab (GET /products/:code/inventory). Neither of those is a product
// record, so nothing about a Stock Receipt save told RTK Query they had gone
// stale: the Stock column kept showing whatever it fetched when the page first
// loaded, and only a full reload corrected it.
//
// The bare 'Product' tag (no id) is deliberate. It invalidates EVERY
// Product-tagged query at once — the list, the CURRENT_STOCK lookup, and each
// per-product `INVENTORY_<code>` entry — which is what is wanted here, because
// a document can move any product and the mutation result does not say which.
// Naming the ids individually would mean re-deriving that list at every call
// site and silently missing whichever one was forgotten.
//
// Applied to all thirteen document types the stock ledger reads (see SOURCES
// in backend/src/utils/stockLedger.js), plus Purchase/Sales Order, which drive
// the Ordered and Committed figures on the Inventory tab's total row.
const STOCK_MOVING_TAGS = ['Product'];

// Saving a Sales Type "Machine" document may have just added a new
// Machineries row for its customer (see backend's
// syncMachineSerialNoToCustomer, run on every Sales Quotation/Order/
// Delivery Challan/Invoice/Return/Credit Memo save) -- without this, the
// Machine Serial No. dropdown on this or another open document for the same
// customer keeps showing the OLD Machineries list until a full page reload,
// since RTK Query has no other way to know that data changed server-side as
// a save side effect rather than through its own mutation. Invalidating the
// whole 'BusinessPartner' type (not a specific id) is deliberately broad --
// this factory has no cheap way to resolve the saved `customer` name string
// to a business partner id here, and re-fetching a couple of Business
// Partner list/detail queries on a Machine-type save is a small, infrequent
// cost next to the alternative (a stale dropdown).
const withMachinerySync = (staticTags = []) => (result) => [
  ...staticTags,
  ...(result?.salesCategory === 'Machine' ? [{ type: 'BusinessPartner' }] : []),
];

// Bespoke Reports > Sales pages are injected straight onto baseApi (see
// features/sales/*ReportApi.js) rather than through createCrudApi, so their
// own tags were never wired into any resource's invalidatesTags — a
// create/update/delete on the documents each report reads from never told
// RTK Query the report's cached rows were now stale. That's why these
// reports (and only these — the plain list/table pages all use each
// resource's ordinary LIST tag, which every mutation already invalidated)
// kept showing rows for documents that had since been edited or deleted,
// until each report's own 45s tab-sync timer (useTabSyncedReportQuery)
// happened to fire. The groups below are added to extraInvalidateTags on
// every resource whose save/delete can change what a given report shows.
//
// Pending Sales Order (getPendingSalesOrderReport) reads SalesOrder joined
// with DeliveryChallan (delivered qty/amount) — see
// /sales/orders/pending/report in resources.js. (The Sales Order Register
// report that used to live alongside this one was renamed/rebuilt as the
// Sales Quotation Register report — see SALES_QUOTATION_REPORT_TAGS below.)
const SALES_ORDER_REPORT_TAGS = [
  { type: 'SalesOrder', id: 'PENDING_REPORT' },
];

// Sales Quotation Register (getSalesQuotationRegisterReport) reads
// SalesQuotation joined with SalesOrder (by quotationNo, to derive whether
// a quotation has been converted) — see /sales/quotations/register/report
// in resources.js. Raising a Sales Order from a quotation also flips that
// quotation's own status (Open -> Closed, see recomputeSalesQuotationStatus
// in documentFlow.js) and its conversionStatus on this report, so
// salesOrderApi needs this tag too, not just salesQuotationApi.
const SALES_QUOTATION_REPORT_TAGS = [
  { type: 'SalesQuotation', id: 'REGISTER_REPORT' },
];

// Sales Invoice Register, Customer-wise/Product-wise/Salesman-wise Sales,
// and Profitability Analysis all read SalesInvoice (+ its items) only — see
// /sales/invoices/register/report, /sales/invoices/customer-wise/report,
// /sales/invoices/product-wise/report, /sales/invoices/salesman-wise/report
// and /sales/invoices/profitability/report. Customer Ledger and Customer
// Aging also key their own tags off 'SalesInvoice' (see those report APIs'
// providesTags) even though they read several receivable documents — that
// wider dependency is CUSTOMER_RECEIVABLE_REPORT_TAGS below.
const SALES_INVOICE_REPORT_TAGS = [
  { type: 'SalesInvoice', id: 'REGISTER_REPORT' },
  { type: 'SalesInvoice', id: 'CUSTOMER_WISE_REPORT' },
  { type: 'SalesInvoice', id: 'PRODUCT_WISE_REPORT' },
  { type: 'SalesInvoice', id: 'SALESMAN_WISE_REPORT' },
  { type: 'SalesInvoice', id: 'PROFITABILITY_REPORT' },
  // Sales tab of Tax Report (getTaxReport's sales query, /sales/tax/report)
  // — reads SalesInvoice (+ items) only.
  { type: 'SalesInvoice', id: 'TAX_REPORT' },
];

// Customer Ledger (getCustomerLedgerReport) and Customer Aging
// (getCustomerAgingReport) — see /receivables/customer-ledger/report and
// /receivables/customer-aging/report — both aggregate SalesInvoice,
// SalesReturn, SalesCreditMemo, Collection and PaymentReceipt together, so
// a save/delete on any one of those five document types can change either
// report's rows or balances. Both reports happen to provide their tags
// under the 'SalesInvoice' tag type (see customerLedgerReportApi.js /
// customerAgingReportApi.js), so this same pair covers both.
// Also carries CustomerOutstanding as a bare type (no id) — Reports >
// Receivables > Customer Outstanding (getCustomerOutstandingReport, see
// /receivables/outstanding/report) reads the exact same materialized
// CustomerOutstanding open-item table Customer Ledger/Aging read from, kept
// in sync server-side off these same five document saves (see
// openItemLedger.js). A bare type invalidates every id under it — both its
// own list (`LIST`, from customerOutstandingApi) and this report's
// (`REPORT`) — in one entry, the same trick STOCK_MOVING_TAGS already
// relies on for 'Product'.
const CUSTOMER_RECEIVABLE_REPORT_TAGS = [
  { type: 'SalesInvoice', id: 'CUSTOMER_LEDGER_REPORT' },
  { type: 'SalesInvoice', id: 'CUSTOMER_AGING_REPORT' },
  { type: 'CustomerOutstanding' },
];

// Purchase Order Register (getPurchaseOrderRegisterReport) and Pending
// Purchase Order (getPendingPurchaseOrderReport) — see
// /purchase/orders/register/report and /purchase/orders/pending/report —
// are the purchase-side mirror of Pending Sales Order (SALES_ORDER_
// REPORT_TAGS above), keyed off PurchaseOrder joined with
// GoodsReceivedNote's received quantity instead of SalesOrder + DeliveryChallan.
// (Unlike the sales side, Purchase Order's own Register report was not
// renamed/rebuilt — it still reads PurchaseOrder directly.)
const PURCHASE_ORDER_REPORT_TAGS = [
  { type: 'PurchaseOrder', id: 'REGISTER_REPORT' },
  { type: 'PurchaseOrder', id: 'PENDING_REPORT' },
];

// Purchase Invoice Register (getPurchaseInvoiceRegisterReport) and the
// Purchase tab of Tax Report (getTaxReport's purchase query) — see
// /purchase/invoices/register/report and /purchase/tax/report — both read
// PurchaseInvoice only, the mirror of SALES_INVOICE_REPORT_TAGS's Register/
// Tax Report entries on the sales side.
const PURCHASE_INVOICE_REPORT_TAGS = [
  { type: 'PurchaseInvoice', id: 'REGISTER_REPORT' },
  { type: 'PurchaseInvoice', id: 'TAX_REPORT' },
];

// Payables > Supplier Outstanding's own Reports page (getSupplierOutstandingReport,
// /payables/outstanding/report) reads the SupplierOutstanding open-item
// table — the payables-side mirror of CustomerOutstanding above, kept in
// sync off PurchaseInvoice/PurchaseReturn/PurchaseCreditMemo/SupplierPayment/
// PaymentVoucher saves. Bare type, same reasoning as CustomerOutstanding.
const SUPPLIER_OUTSTANDING_TAGS = [{ type: 'SupplierOutstanding' }];

// Enquiry Register (getEnquiryRegisterReport) and Enquiry Analysis
// (getEnquiryAnalysisReport) — see /sales/enquiries/register/report and
// /sales/enquiries/analysis/report — both read the Enquiry resource only.
// Also added to salesQuotationApi below: an Enquiry's own status flips
// Open -> Closed the moment a Sales Quotation quotes it server-side (see
// recomputeEnquiryStatus in utils/documentFlow.js), so a quotation save can
// change these reports' rows without the Enquiry resource's own mutations
// ever firing.
const ENQUIRY_REPORT_TAGS = [
  { type: 'Enquiry', id: 'REGISTER_REPORT' },
  { type: 'Enquiry', id: 'ANALYSIS_REPORT' },
];

// Cash Book, Bank Book and Day Book (getCashBookReport/getBankBookReport/
// getDayBookReport — /banking/cash-book/report, /banking/bank-book/report,
// /banking/day-book/report) all build their ledger rows from Collection +
// SupplierPayment. Cash Book's own opening-balance helper
// (computeCashBalanceAsOf) additionally nets out Cheque and BankDeposit
// movements against the House Bank baseline, so those two also carry this
// group below (all three tags, for simplicity, even though Cheque/
// BankDeposit only ever actually move Cash Book's own opening balance).
const CASH_LEDGER_REPORT_TAGS = [
  { type: 'Collection', id: 'CASH_BOOK_REPORT' },
  { type: 'Collection', id: 'BANK_BOOK_REPORT' },
  { type: 'Collection', id: 'DAY_BOOK_REPORT' },
];

export const salesReturnApi = createCrudApi({ resourcePath: 'sales/returns', tagType: 'SalesReturn', extraInvalidateTags: withMachinerySync([...STOCK_MOVING_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS]) });

// Bulk "Import from Excel" + "Download Template" for Sales Return — same
// hand-injected shape as Sales Invoice's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate SalesReturn's LIST tag automatically when a page does use them).
const salesReturnBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importSalesReturnsXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/returns/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'SalesReturn', id: 'LIST' }, ...STOCK_MOVING_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS],
    }),
    downloadSalesReturnBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/returns/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportSalesReturnsXlsxMutation = salesReturnBulkImportApi.useImportSalesReturnsXlsxMutation;
export const useDownloadSalesReturnBulkImportTemplateMutation = salesReturnBulkImportApi.useDownloadSalesReturnBulkImportTemplateMutation;

export const salesCreditMemoApi = createCrudApi({ resourcePath: 'sales/credit-memos', tagType: 'SalesCreditMemo', extraInvalidateTags: withMachinerySync([...STOCK_MOVING_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS]) });

// Bulk "Import from Excel" + "Download Template" for Sales Credit Memo — same
// hand-injected shape as Sales Return's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate SalesCreditMemo's LIST tag automatically when a page does use them).
const salesCreditMemoBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importSalesCreditMemosXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/credit-memos/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'SalesCreditMemo', id: 'LIST' }, ...STOCK_MOVING_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS],
    }),
    downloadSalesCreditMemoBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/credit-memos/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportSalesCreditMemosXlsxMutation = salesCreditMemoBulkImportApi.useImportSalesCreditMemosXlsxMutation;
export const useDownloadSalesCreditMemoBulkImportTemplateMutation = salesCreditMemoBulkImportApi.useDownloadSalesCreditMemoBulkImportTemplateMutation;

export const purchaseCreditMemoApi = createCrudApi({ resourcePath: 'purchase/credit-memos', tagType: 'PurchaseCreditMemo', extraInvalidateTags: [...STOCK_MOVING_TAGS, ...SUPPLIER_OUTSTANDING_TAGS] });

export const purchaseReturnApi = createCrudApi({ resourcePath: 'purchase/returns', tagType: 'PurchaseReturn', extraInvalidateTags: [...STOCK_MOVING_TAGS, ...SUPPLIER_OUTSTANDING_TAGS] });

// Full CRUD, backed by routes/users.js (not the generic crudRouter — see that
// file for why: password hashing and each user's nested permission grid).
// useList is also what every "assigned to"/"received by" style dropdown
// elsewhere in the app (Collection Entry, etc.) calls.
export const appUserApi = createCrudApi({ resourcePath: 'users', tagType: 'AppUser' });

// Purchase
// extraInvalidateTags: Reports > Purchase > Price Comparison
// (getPriceComparisonReport, /purchase/quotations/price-comparison/report)
// reads PurchaseQuotation only.
export const purchaseQuotationApi = createCrudApi({ resourcePath: 'purchase/quotations', tagType: 'PurchaseQuotation', extraInvalidateTags: [{ type: 'PurchaseQuotation', id: 'PRICE_COMPARISON_REPORT' }] });

// Bulk "Import from Excel" + "Download Template" for Purchase Quotation —
// same hand-injected shape as Sales Invoice's/Purchase Order's own
// bulk-import endpoints above (see the Purchase Order comment for the full
// rationale). BulkImportDialog.jsx itself doesn't use these — it's a plain
// `fetch` so it stays resource-agnostic — these exist for any page that
// wants a typed RTK Query hook instead (and to invalidate PurchaseQuotation's
// LIST tag automatically when a page does use them).
const purchaseQuotationBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importPurchaseQuotationsXlsx: builder.mutation({
      query: (formData) => ({ url: '/purchase/quotations/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'PurchaseQuotation', id: 'LIST' }, { type: 'PurchaseQuotation', id: 'PRICE_COMPARISON_REPORT' }],
    }),
    downloadPurchaseQuotationBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/purchase/quotations/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportPurchaseQuotationsXlsxMutation = purchaseQuotationBulkImportApi.useImportPurchaseQuotationsXlsxMutation;
export const useDownloadPurchaseQuotationBulkImportTemplateMutation = purchaseQuotationBulkImportApi.useDownloadPurchaseQuotationBulkImportTemplateMutation;

// A purchase order doesn't move stock, but it is what "Ordered" on the
// Inventory tab counts — so it invalidates the same tag.
export const purchaseOrderApi = createCrudApi({ resourcePath: 'purchase/orders', tagType: 'PurchaseOrder', extraInvalidateTags: [...STOCK_MOVING_TAGS, ...PURCHASE_ORDER_REPORT_TAGS] });

// Bulk "Import from Excel" + "Download Template" for Purchase Order — same
// hand-injected shape as Sales Invoice's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate PurchaseOrder's LIST tag automatically when a page does use them).
const purchaseOrderBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importPurchaseOrdersXlsx: builder.mutation({
      query: (formData) => ({ url: '/purchase/orders/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'PurchaseOrder', id: 'LIST' }, ...STOCK_MOVING_TAGS, ...PURCHASE_ORDER_REPORT_TAGS],
    }),
    downloadPurchaseOrderBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/purchase/orders/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportPurchaseOrdersXlsxMutation = purchaseOrderBulkImportApi.useImportPurchaseOrdersXlsxMutation;
export const useDownloadPurchaseOrderBulkImportTemplateMutation = purchaseOrderBulkImportApi.useDownloadPurchaseOrderBulkImportTemplateMutation;
// Also invalidates PURCHASE_ORDER_REPORT_TAGS: a GRN's received quantity is
// what Purchase Order Register/Pending Purchase Order join in against the
// order (see the comment on that constant above), so saving/deleting a GRN
// can change an order's delivery status or pending qty on those reports
// even though the PurchaseOrder row itself didn't change.
export const goodsReceivedNoteApi = createCrudApi({ resourcePath: 'purchase/grn', tagType: 'GoodsReceivedNote', extraInvalidateTags: [...STOCK_MOVING_TAGS, ...PURCHASE_ORDER_REPORT_TAGS] });
export const purchaseInvoiceApi = createCrudApi({ resourcePath: 'purchase/invoices', tagType: 'PurchaseInvoice', extraInvalidateTags: [...STOCK_MOVING_TAGS, ...PURCHASE_INVOICE_REPORT_TAGS, ...SUPPLIER_OUTSTANDING_TAGS] });

// Sales
export const salesQuotationApi = createCrudApi({ resourcePath: 'sales/quotations', tagType: 'SalesQuotation', extraInvalidateTags: withMachinerySync([...ENQUIRY_REPORT_TAGS, ...SALES_QUOTATION_REPORT_TAGS]) });

// Bulk "Import from Excel" + "Download Template" for Sales Quotation — same
// hand-injected shape as Sales Invoice's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate SalesQuotation's LIST tag automatically when a page does use them).
const salesQuotationBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importSalesQuotationsXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/quotations/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'SalesQuotation', id: 'LIST' }, ...SALES_QUOTATION_REPORT_TAGS],
    }),
    downloadSalesQuotationBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/quotations/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportSalesQuotationsXlsxMutation = salesQuotationBulkImportApi.useImportSalesQuotationsXlsxMutation;
export const useDownloadSalesQuotationBulkImportTemplateMutation = salesQuotationBulkImportApi.useDownloadSalesQuotationBulkImportTemplateMutation;
// Same as Purchase Order above: drives "Committed", not on-hand. Also
// invalidates SALES_QUOTATION_REPORT_TAGS: raising a Sales Order from a
// quotation flips that quotation's own status (see
// recomputeSalesQuotationStatus in documentFlow.js) and its
// conversionStatus/convertedOrderNo on the Sales Quotation Register report,
// even though no SalesQuotation row itself was touched by this mutation.
export const salesOrderApi = createCrudApi({ resourcePath: 'sales/orders', tagType: 'SalesOrder', extraInvalidateTags: withMachinerySync([...STOCK_MOVING_TAGS, ...SALES_ORDER_REPORT_TAGS, ...SALES_QUOTATION_REPORT_TAGS]) });

// Bulk "Import from Excel" + "Download Template" for Sales Order — same
// hand-injected shape as Sales Invoice's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate SalesOrder's LIST tag automatically when a page does use them).
const salesOrderBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importSalesOrdersXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/orders/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'SalesOrder', id: 'LIST' }, ...STOCK_MOVING_TAGS, ...SALES_ORDER_REPORT_TAGS, ...SALES_QUOTATION_REPORT_TAGS],
    }),
    downloadSalesOrderBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/orders/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportSalesOrdersXlsxMutation = salesOrderBulkImportApi.useImportSalesOrdersXlsxMutation;
export const useDownloadSalesOrderBulkImportTemplateMutation = salesOrderBulkImportApi.useDownloadSalesOrderBulkImportTemplateMutation;

// Also invalidates SALES_ORDER_REPORT_TAGS: both reports join in each
// order's delivered qty/amount from DeliveryChallan (see the comment on
// SALES_ORDER_REPORT_TAGS above), so saving/deleting a challan can change
// an order's delivery status or pending amount on those reports even
// though the SalesOrder row itself didn't change.
export const deliveryChallanApi = createCrudApi({ resourcePath: 'sales/delivery-challans', tagType: 'DeliveryChallan', extraInvalidateTags: withMachinerySync([...STOCK_MOVING_TAGS, ...SALES_ORDER_REPORT_TAGS]) });

// Bulk "Import from Excel" + "Download Template" for Delivery Challan — same
// hand-injected shape as Sales Invoice's own bulk-import endpoints above (see
// that comment for the full rationale). BulkImportDialog.jsx itself doesn't
// use these — it's a plain `fetch` so it stays resource-agnostic — these
// exist for any page that wants a typed RTK Query hook instead (and to
// invalidate DeliveryChallan's LIST tag automatically when a page does use them).
const deliveryChallanBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importDeliveryChallansXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/delivery-challans/bulk-import', method: 'POST', body: formData }),
      invalidatesTags: [{ type: 'DeliveryChallan', id: 'LIST' }, ...STOCK_MOVING_TAGS, ...SALES_ORDER_REPORT_TAGS],
    }),
    downloadDeliveryChallanBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/delivery-challans/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportDeliveryChallansXlsxMutation = deliveryChallanBulkImportApi.useImportDeliveryChallansXlsxMutation;
export const useDownloadDeliveryChallanBulkImportTemplateMutation = deliveryChallanBulkImportApi.useDownloadDeliveryChallanBulkImportTemplateMutation;
// extraInvalidateTags also carries every Reports > Sales page's own cache
// tag that reads SalesInvoice data (SALES_INVOICE_REPORT_TAGS: Register,
// Customer-wise/Product-wise/Salesman-wise Sales, Profitability; plus
// CUSTOMER_RECEIVABLE_REPORT_TAGS for Customer Ledger/Aging — see the doc
// comments on those constants above). Each is a bespoke query injected
// straight onto baseApi rather than going through createCrudApi, so none of
// their tags were ever wired into this mutation's invalidatesTags before.
// Without this, RTK Query had no way to know a create/update/delete here
// changed any of those reports' underlying data: each kept serving its
// last-cached rows -- including ones for an invoice that had just been
// deleted -- until its own 45s tab-sync timer (see useTabSyncedReportQuery)
// happened to fire, rather than refreshing right away like every other
// Sales Invoice list/table does.
export const salesInvoiceApi = createCrudApi({ resourcePath: 'sales/invoices', tagType: 'SalesInvoice', extraInvalidateTags: withMachinerySync([...STOCK_MOVING_TAGS, ...SALES_INVOICE_REPORT_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS]) });

// Sales Invoice > "E-Invoice / E-Way Bill" tab — TaxPro GSP actions (see
// services/taxproGsp.service.js). Hand-injected like postJournalEntryToGl
// above: each acts on an existing invoice and returns the updated row, not
// one of createCrudApi's generic list/create/update/delete shapes.
const salesInvoiceEDocsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    generateEInvoice: builder.mutation({
      query: (id) => ({ url: `/sales/invoices/${id}/einvoice/generate`, method: 'POST' }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, id) => [{ type: 'SalesInvoice', id }],
    }),
    cancelEInvoice: builder.mutation({
      query: ({ id, cancelReason }) => ({ url: `/sales/invoices/${id}/einvoice/cancel`, method: 'POST', body: { cancelReason } }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'SalesInvoice', id }],
    }),
    generateEWayBill: builder.mutation({
      query: ({ id, ...body }) => ({ url: `/sales/invoices/${id}/eway-bill/generate`, method: 'POST', body }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'SalesInvoice', id }],
    }),
    cancelEWayBill: builder.mutation({
      query: ({ id, cancelReason }) => ({ url: `/sales/invoices/${id}/eway-bill/cancel`, method: 'POST', body: { cancelReason } }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'SalesInvoice', id }],
    }),
  }),
  overrideExisting: false,
});
// Sales Invoice print-copy tracking — see the /sales/invoices/:id/mark-printed
// and /reset-printed routes in backend/src/routes/resources.js.
const salesInvoicePrintApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    markSalesInvoicePrinted: builder.mutation({
      query: (id) => ({ url: `/sales/invoices/${id}/mark-printed`, method: 'POST' }),
      invalidatesTags: (result, error, id) => [{ type: 'SalesInvoice', id }, { type: 'SalesInvoice', id: 'LIST' }],
    }),
    resetSalesInvoicePrinted: builder.mutation({
      query: (id) => ({ url: `/sales/invoices/${id}/reset-printed`, method: 'POST' }),
      invalidatesTags: (result, error, id) => [{ type: 'SalesInvoice', id }, { type: 'SalesInvoice', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useMarkSalesInvoicePrintedMutation = salesInvoicePrintApi.useMarkSalesInvoicePrintedMutation;
export const useResetSalesInvoicePrintedMutation = salesInvoicePrintApi.useResetSalesInvoicePrintedMutation;
export const useGenerateEInvoiceMutation = salesInvoiceEDocsApi.useGenerateEInvoiceMutation;
export const useCancelEInvoiceMutation = salesInvoiceEDocsApi.useCancelEInvoiceMutation;
export const useGenerateEWayBillMutation = salesInvoiceEDocsApi.useGenerateEWayBillMutation;
export const useCancelEWayBillMutation = salesInvoiceEDocsApi.useCancelEWayBillMutation;

// "Send via WhatsApp" -- Sales Quotation / Sales Invoice. The PDF is built
// client-side (see captureSalesQuotationPdf/captureSalesInvoicePdf in
// components/print) and posted as a multipart file, same FormData-body
// pattern as importDeliveryChallansXlsx above -- body is the FormData
// itself, not JSON, since it's already what the caller assembled (file +
// bodyParams). Each caller builds `formData` with a 'file' (the PDF Blob)
// and a 'bodyParams' field (a JSON-encoded array of the template's body
// {{n}} values) before calling the mutation.
const salesWhatsAppApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    sendSalesQuotationWhatsApp: builder.mutation({
      query: ({ id, formData }) => ({ url: `/sales/quotations/${id}/whatsapp/send`, method: 'POST', body: formData }),
    }),
    sendSalesInvoiceWhatsApp: builder.mutation({
      query: ({ id, formData }) => ({ url: `/sales/invoices/${id}/whatsapp/send`, method: 'POST', body: formData }),
    }),
  }),
  overrideExisting: false,
});
export const useSendSalesQuotationWhatsAppMutation = salesWhatsAppApi.useSendSalesQuotationWhatsAppMutation;
export const useSendSalesInvoiceWhatsAppMutation = salesWhatsAppApi.useSendSalesInvoiceWhatsAppMutation;

// Same FormData-body pattern as salesWhatsAppApi above, for Payment
// Receipt (Incoming Payment) / Payment Voucher (Outgoing Payment).
const paymentWhatsAppApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    sendPaymentReceiptWhatsApp: builder.mutation({
      query: ({ id, formData }) => ({ url: `/banking/payment-receipts/${id}/whatsapp/send`, method: 'POST', body: formData }),
    }),
    sendPaymentVoucherWhatsApp: builder.mutation({
      query: ({ id, formData }) => ({ url: `/banking/payment-vouchers/${id}/whatsapp/send`, method: 'POST', body: formData }),
    }),
  }),
  overrideExisting: false,
});
export const useSendPaymentReceiptWhatsAppMutation = paymentWhatsAppApi.useSendPaymentReceiptWhatsAppMutation;
export const useSendPaymentVoucherWhatsAppMutation = paymentWhatsAppApi.useSendPaymentVoucherWhatsAppMutation;

// Bulk "Import from Excel" + "Download Template" for Sales Invoice — the
// reference implementation of the pattern the other 11 document types (Sales
// Order/Quotation/Delivery Challan/Return/Credit Memo, the six Purchase
// documents) are meant to copy. Same hand-injected shape as Chart of
// Accounts' own import endpoints above: the import is a multipart upload
// (`body: formData` lets fetchBaseQuery skip JSON.stringify-ing it and leave
// the multipart Content-Type/boundary to the browser) and the template is a
// server-generated binary file, so its query overrides `responseHandler` to
// hand back a Blob instead of letting fetchBaseQuery try to parse it as
// JSON. BulkImportDialog.jsx itself doesn't use these — it's a plain `fetch`
// so it stays resource-agnostic — these exist for any page that wants a
// typed RTK Query hook instead (and to invalidate SalesInvoice's LIST tag
// automatically when a page does use them).
const salesInvoiceBulkImportApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    importSalesInvoicesXlsx: builder.mutation({
      query: (formData) => ({ url: '/sales/invoices/bulk-import', method: 'POST', body: formData }),
      // Also invalidates every Reports > Sales tag salesInvoiceApi above
      // does, so newly-imported invoices show up there immediately instead
      // of only in the plain list.
      invalidatesTags: [{ type: 'SalesInvoice', id: 'LIST' }, ...SALES_INVOICE_REPORT_TAGS, ...CUSTOMER_RECEIVABLE_REPORT_TAGS, ...STOCK_MOVING_TAGS],
    }),
    downloadSalesInvoiceBulkImportTemplate: builder.mutation({
      query: () => ({
        url: '/sales/invoices/bulk-import/template',
        method: 'GET',
        responseHandler: (response) => response.blob(),
        cache: 'no-cache',
      }),
    }),
  }),
  overrideExisting: false,
});
export const useImportSalesInvoicesXlsxMutation = salesInvoiceBulkImportApi.useImportSalesInvoicesXlsxMutation;
export const useDownloadSalesInvoiceBulkImportTemplateMutation = salesInvoiceBulkImportApi.useDownloadSalesInvoiceBulkImportTemplateMutation;

export const enquiryApi = createCrudApi({ resourcePath: 'sales/enquiries', tagType: 'Enquiry', extraInvalidateTags: ENQUIRY_REPORT_TAGS });
export const followUpApi = createCrudApi({ resourcePath: 'sales/follow-ups', tagType: 'FollowUp' });

// Inventory
export const stockReceiptApi = createCrudApi({ resourcePath: 'inventory/stock-receipts', tagType: 'StockReceipt', extraInvalidateTags: STOCK_MOVING_TAGS });
export const stockIssueApi = createCrudApi({ resourcePath: 'inventory/stock-issues', tagType: 'StockIssue', extraInvalidateTags: STOCK_MOVING_TAGS });
export const stockAdjustmentApi = createCrudApi({ resourcePath: 'inventory/stock-adjustments', tagType: 'StockAdjustment', extraInvalidateTags: STOCK_MOVING_TAGS });
export const stockTransferApi = createCrudApi({ resourcePath: 'inventory/stock-transfers', tagType: 'StockTransfer', extraInvalidateTags: STOCK_MOVING_TAGS });

// Stock Transfer Issue > "E-Way Bill" tab (Branch Transfer) -- the same two
// TaxPro GSP actions as salesInvoiceEDocsApi above, against the Stock
// Transfer routes (see taxproGsp.service.js generateStockTransferEWayBill).
// Each acts on a saved transfer and returns the updated row.
const stockTransferEWayApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    generateStockTransferEWayBill: builder.mutation({
      query: ({ id, ...body }) => ({ url: `/inventory/stock-transfers/${id}/eway-bill/generate`, method: 'POST', body }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'StockTransfer', id }, { type: 'StockTransfer', id: 'LIST' }],
    }),
    cancelStockTransferEWayBill: builder.mutation({
      query: ({ id, cancelReason }) => ({ url: `/inventory/stock-transfers/${id}/eway-bill/cancel`, method: 'POST', body: { cancelReason } }),
      transformResponse: (response) => response.data,
      invalidatesTags: (result, error, { id }) => [{ type: 'StockTransfer', id }, { type: 'StockTransfer', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const useGenerateStockTransferEWayBillMutation = stockTransferEWayApi.useGenerateStockTransferEWayBillMutation;
export const useCancelStockTransferEWayBillMutation = stockTransferEWayApi.useCancelStockTransferEWayBillMutation;
export const stockTransferRequestApi = createCrudApi({ resourcePath: 'inventory/stock-transfer-requests', tagType: 'StockTransferRequest' });
export const stockTransferReceiptApi = createCrudApi({ resourcePath: 'inventory/stock-transfer-receipts', tagType: 'StockTransferReceipt' });

// Receivables
export const customerOutstandingApi = createCrudApi({ resourcePath: 'receivables/outstanding', tagType: 'CustomerOutstanding' });
// Saving/deleting a collection makes the backend silently upsert/remove a
// matching BankReconciliationTransaction row (syncBankReconciliationTxn) —
// invalidate BankReconciliation's list too, or the Bank Reconciliation page
// keeps showing stale System Transactions until a manual refresh.
// Also invalidates CUSTOMER_RECEIVABLE_REPORT_TAGS -- Customer Ledger and
// Customer Aging both aggregate Collection rows alongside SalesInvoice/
// SalesReturn/SalesCreditMemo/PaymentReceipt (see the comment on that
// constant above), so a saved/deleted collection can move either report's
// balances even though no SalesInvoice row changed.
// Also carries CASH_LEDGER_REPORT_TAGS -- Cash Book/Bank Book/Day Book all
// read Collection rows directly (see that constant's comment above) -- and
// Collection Register's own tag (getCollectionRegisterReport, see
// /receivables/collection-register/report), which reads Collection only.
export const collectionApi = createCrudApi({ resourcePath: 'receivables/collections', tagType: 'Collection', extraInvalidateTags: [{ type: 'BankReconciliation', id: 'LIST' }, { type: 'Collection', id: 'REGISTER_REPORT' }, ...CUSTOMER_RECEIVABLE_REPORT_TAGS, ...CASH_LEDGER_REPORT_TAGS] });

// Payables
export const supplierOutstandingApi = createCrudApi({ resourcePath: 'payables/outstanding', tagType: 'SupplierOutstanding' });
// Same reasoning as collectionApi above — supplier payments sync a
// BankReconciliationTransaction row server-side.
// Also carries Payment Register's own tag (getPaymentRegisterReport,
// /payables/payment-register/report — reads SupplierPayment only),
// SUPPLIER_OUTSTANDING_TAGS (a payment settles/reopens supplier open
// items), and CASH_LEDGER_REPORT_TAGS (Cash Book/Bank Book/Day Book all
// read SupplierPayment rows directly).
export const supplierPaymentApi = createCrudApi({ resourcePath: 'payables/payments', tagType: 'SupplierPayment', extraInvalidateTags: [{ type: 'BankReconciliation', id: 'LIST' }, { type: 'SupplierPayment', id: 'REGISTER_REPORT' }, ...SUPPLIER_OUTSTANDING_TAGS, ...CASH_LEDGER_REPORT_TAGS] });

// Banking
// Same reasoning as collectionApi/supplierPaymentApi above — bank deposits
// and cheques both sync a BankReconciliationTransaction row server-side.
// Also carries Deposit Register's own tag (getDepositRegisterReport,
// /banking/deposit-register/report — reads BankDeposit only) and
// CASH_LEDGER_REPORT_TAGS (Cash Book's own opening-balance helper nets out
// BankDeposit movements — see that constant's comment above).
export const bankDepositApi = createCrudApi({ resourcePath: 'banking/deposits', tagType: 'BankDeposit', extraInvalidateTags: [{ type: 'BankReconciliation', id: 'LIST' }, { type: 'BankDeposit', id: 'REGISTER_REPORT' }, ...CASH_LEDGER_REPORT_TAGS] });
export const bankReconciliationApi = createCrudApi({ resourcePath: 'banking/reconciliations', tagType: 'BankReconciliation' });
// Also carries CASH_LEDGER_REPORT_TAGS -- Cash Book's own opening-balance
// helper nets out Cheque movements (see that constant's comment above).
export const chequeApi = createCrudApi({ resourcePath: 'banking/cheques', tagType: 'Cheque', extraInvalidateTags: [{ type: 'BankReconciliation', id: 'LIST' }, ...CASH_LEDGER_REPORT_TAGS] });
// Payment Receipt ("Incoming Payment") -- posts against a Customer, Vendor,
// or raw Account. Unlike the deposit/cheque/collection/payment resources
// above, it has no bank-account field of its own to sync a
// BankReconciliationTransaction against, so it carries no extraInvalidateTags.
// Also invalidates CUSTOMER_RECEIVABLE_REPORT_TAGS -- same reasoning as
// collectionApi above: a customer-facing Payment Receipt is one of the five
// document types Customer Ledger/Aging aggregate.
export const paymentReceiptApi = createCrudApi({ resourcePath: 'banking/payment-receipts', tagType: 'PaymentReceipt', extraInvalidateTags: CUSTOMER_RECEIVABLE_REPORT_TAGS });
// Payment Voucher ("Outgoing Payment") -- same no-bank-reconciliation-sync
// reasoning as paymentReceiptApi above.
// Also carries SUPPLIER_OUTSTANDING_TAGS -- a Payment Voucher is one of the
// five document types the SupplierOutstanding open-item table is kept in
// sync from (see that constant's comment above), the payables-side mirror
// of paymentReceiptApi below.
export const paymentVoucherApi = createCrudApi({ resourcePath: 'banking/payment-vouchers', tagType: 'PaymentVoucher', extraInvalidateTags: SUPPLIER_OUTSTANDING_TAGS });

// Route Map — the whole document chain one purchase/sales document belongs to,
// for the Route Map dialog on every Purchase and Sales list page.
//
// Not a CRUD resource: it is a read-only view across seven tables, keyed by the
// document it was opened on rather than by an id of its own.
//
// Deliberately carries no cache tag. The chain spans thirteen resources, so
// tagging it would mean adding an invalidation to all thirteen CRUD apis and
// still missing whichever one gets added next — a stale route map that quietly
// omits the invoice somebody just raised is worse than an extra request. The
// dialog passes refetchOnMountOrArgChange instead, so every open re-reads.
const routeMapApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getRouteMap: builder.query({
      query: ({ flow, type, no }) => ({
        url: `/${flow}/route-map`,
        params: { type, no },
      }),
      transformResponse: (response) => response.data,
    }),
  }),
  overrideExisting: false,
});
export const useGetRouteMapQuery = routeMapApi.useGetRouteMapQuery;

// Notification bell — hand-injected rather than generated by createCrudApi:
// this is scoped to the current user (no id-based CRUD) and two of its four
// endpoints (approve/reject) act on an existing record with no body, same
// reasoning as journalEntryPostApi above.
//
// The list is kept fresh WITHOUT refetching: real-time socket events carry
// their data and are spliced into this cache by lib/useNotificationSocket.js,
// and the three mutations below patch the affected row locally on success
// (instead of invalidating the list, which would cost a GET per click). Both
// patch the cache entry for the `undefined` arg, the exact arg Header.jsx
// queries with.
const patchNotification = (draft, id, changes) => {
  const row = draft.data.find((n) => n.id === id);
  if (!row) return;
  if (row.status === 'Unread' && changes.status === 'Read') draft.unreadCount = Math.max(0, (draft.unreadCount || 0) - 1);
  Object.assign(row, changes);
};
const patchOnSuccess = (changes) => async (id, { dispatch, queryFulfilled }) => {
  try {
    const { data } = await queryFulfilled;
    // An orphaned request resolves as a normal success but comes back
    // 'Cancelled' (see resolveApproval) -- show that, not the clicked decision.
    const applied = changes.actionStatus && data?.actionStatus === 'Cancelled' ? { ...changes, actionStatus: 'Cancelled' } : changes;
    dispatch(notificationApi.util.updateQueryData('getNotifications', undefined, (draft) => patchNotification(draft, id, applied)));
  } catch {
    // A failed mutation changes nothing; the caller surfaces the error.
  }
};

export const notificationApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    getNotifications: builder.query({
      query: (params) => ({ url: '/notifications', params }),
      transformResponse: (response) => ({ data: response.data, unreadCount: response.unreadCount }),
      providesTags: [{ type: 'Notification', id: 'LIST' }],
    }),
    markNotificationRead: builder.mutation({
      query: (id) => ({ url: `/notifications/${id}/read`, method: 'PATCH' }),
      transformResponse: (response) => response.data,
      onQueryStarted: patchOnSuccess({ status: 'Read' }),
    }),
    approveNotification: builder.mutation({
      query: (id) => ({ url: `/notifications/${id}/approve`, method: 'POST' }),
      transformResponse: (response) => response.data,
      onQueryStarted: patchOnSuccess({ status: 'Read', actionStatus: 'Approved' }),
      invalidatesTags: [{ type: 'StockTransferRequest', id: 'LIST' }],
    }),
    rejectNotification: builder.mutation({
      query: (id) => ({ url: `/notifications/${id}/reject`, method: 'POST' }),
      transformResponse: (response) => response.data,
      onQueryStarted: patchOnSuccess({ status: 'Read', actionStatus: 'Rejected' }),
      invalidatesTags: [{ type: 'StockTransferRequest', id: 'LIST' }],
    }),
  }),
  overrideExisting: false,
});
export const {
  useGetNotificationsQuery,
  useMarkNotificationReadMutation,
  useApproveNotificationMutation,
  useRejectNotificationMutation,
} = notificationApi;
